FROM nvcr.io/nvidia/pytorch:21.10-py3

# Accept build arguments for user/group IDs
ARG USER_ID
ARG GROUP_ID
ARG USER_NAME=userapp

# Install system-wide packages
RUN pip install \
    huggingface_hub==0.26.1 \
    datasets==3.0.2 \
    nvidia-ml-py3==7.352.0  \
    transformers==4.46.0

RUN pip install -U kaleido==0.2.1

# Install system dependencies for FastMoE
RUN apt-get update && apt-get install -y \
    git \
    cmake \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

# Clone and install SmartMoE
RUN git clone https://github.com/thu-pacman/SmartMoE-AE.git /workspace/smartmoe && \
    cd /workspace/smartmoe && \
    git checkout e19b3a994db5f7614778fd02c48f602ba9d9ac6e && \
    cd /workspace/smartmoe/src/fastmoe && \
    sed -i "s/name='fastmoe'/name='smartmoe'/" setup.py && \
    git submodule update --init --recursive && \
    USE_NCCL=1 /opt/smartmoe_env/bin/pip install .

# Create Triton directory
RUN mkdir -p /.triton/autotune

RUN groupadd -f -g ${GROUP_ID} ${USER_NAME} || true && \
    id -u ${USER_NAME} >/dev/null 2>&1 || useradd -l -u ${USER_ID} -g ${GROUP_ID} ${USER_NAME} && \
    install -d -m 0755 -o ${USER_NAME} -g ${USER_NAME} /home/${USER_NAME}

# Create directory for non-root pip installations
RUN mkdir -p /home/${USER_NAME}/.local && \
    chown -R ${USER_NAME}:${USER_NAME} /home/${USER_NAME}/.local

# Set environment variables
ENV PATH="/home/${USER_NAME}/.local/bin:${PATH}"

# Switch to non-root user
USER ${USER_NAME}

# Set the working directory
WORKDIR /workspace